### ISSUE TITLE
Add Friendly Corps logo and link to the top right of the page.

### ISSUE THREAD

**Issue by pichot** [friendlycode/homepage#4]
It was on the old site, but didn't have the time to get it up on the new site.

**Comment by joel6653** [comment]
Really? Opened 3 years ago? We don't even have the same "homepage" any more, do we? Close, or what?

**Comment by Allen616** [comment]
This is not the same homepage also is not consensus on the logo.

**Comment by pichot** [comment]
Ha! Ya, super old. I'll close it.
